version: "3"
services:
  app:
    build: .
    container_name: tmp_system
    working_dir: /usr/src/app
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 8082:8080
    volumes:
      - .:/usr/src/app
      - app:/usr/src/app/node_modules
    depends_on:
      - postgres
    command: npm start
  postgres:
    image: postgres:12
    container_name: temp_db
    restart: always
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: temp
      POSTGRES_PASSWORD: TokiwaKanoWayo
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: educate@alicey.dev
      PGADMIN_DEFAULT_PASSWORD: TokiwaKanoWayo
    ports:
      - 8083:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
  app:
  postgres:
  pgadmin:
